const DELETE_API_REQUEST = 'DELETE_API_REQUEST';
const DELETE_API_SUCCESS = 'DELETE_API_SUCCESS';
const DELETE_API_FAILURE = 'DELETE_API_FAILURE';


export {
  DELETE_API_REQUEST,
  DELETE_API_SUCCESS,
  DELETE_API_FAILURE,
}
